name: 'Kubernetes Log Export Action'
description: 'Exports Kubernetes logs and generates a file tree for use with https://stoat.dev/'
author: 'Stoat Dev'
branding:
  icon: 'sun'
  color: 'white'
inputs:
  show_timestamps:
    default: 'true'
    description: if 'true', each log line will be prefixed with the Kubernetes timestamp. if 'false', no prefix.
  output_dir:
    default: ./kubernetes-logs
    description: the directory you want to export your logs into
runs:
  using: 'node16'
  command: |
    chmod +x kubelogs.sh
    node /dist/index.js
